### ISSUE TITLE
How do I set up the valueChanged event?

### ISSUE THREAD

**Issue by MassMessage** [bdimitrijoski/clean-web-ui-property-grid#9]
Where do I do that? I've tried as member of options and setting in the property grid itself but I didn't see anything being fired in the console.

I've tried:

     ```const pgOptions = {
            preferredFormat: 'hex',
            showInput: true,
            showInitial: true,
            hasGroups: true,
            propertySort: true,
            toolbarVisible: true,

            onValueChange: (e) => {
                //console.log(e);
                //console.log('id = ', e.target.name)
                if (e.target.id === 'pgfilter2')
                {
                    e.preventDefault();
                    e.stopPropagation();
                    return false;
                }
            },

            valueChanged: (data) => {
                console.log('editing done! data = ', data)
            }
        }; 
```
even:

```
        const pg = document.getElementById('pg1')
        pg.valueChanged = (data) => {
            console.log('editing done! data = ', data)
        }
```

neither work. How am I supposed to do that?

**Comment by bdimitrijoski** [comment]
You can listen for value changed event like this: 
```
document.getElementById('pgpropertyGridWithConfig').addEventListener('valueChange', (v) => console.log(v));
```

Take a look this sample here:
src/sample/index.js

Reading this, probably I should update the readme and add more examples there.

**Comment by MassMessage** [comment]
> 
> 
> You can listen for value changed event like this:
> 
> ```
> document.getElementById('pgpropertyGridWithConfig').addEventListener('valueChanged', (v) => console.log(v));
> ```

works like a charm, thanks!

> Take a look this sample here:
> src/sample/index.js

ops, I missed this one

> Reading this, probably I should update the readme and add more examples there.

I think that's a good idea
